language: node_js
sudo: true
node_js:
  - "14"
  - "16"
dist: focal
before_install:
  - npm install -g npm@^6
  - chmod 777 ./setup/travis/travis-redis.sh
  - ./setup/travis/travis-redis.sh
before_script:
  - npm install -g grunt-cli
  - grunt css
addons:
  chrome: stable
